### PR TITLE
Fix python 2.6 compability issue

### PR DESCRIPTION
**Pull request by rudineirk**

### CODE REVIEW

**Comment by samstav** [comment]
Hey @rudineirk, thanks for the fix! Can you post the traceback/error you encountered in this PR description? Was it a `ValueError`?

Pulling the logs from circle where we got a failure:

```
New python executable in /home/ubuntu/tox-pyenv/.tox/py32/bin/python3.2
Also creating executable in /home/ubuntu/tox-pyenv/.tox/py32/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/ubuntu/tox-pye...x/py32/bin/python3.2 - setuptools pip wheel:
  /home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/mercurial.py", line 9, in <module>
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/download.py", line 36, in <module>
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/utils/ui.py", line 15, in <module>
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 2316, in <module>
    main()
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 708, in main
    symlink=options.symlink)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 941, in create_environment
    download=download,
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 897, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/virtualenv.py", line 792, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ubuntu/tox-pye...x/py32/bin/python3.2 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /home/ubuntu/.pyenv/versions/3.2.5/bin/python3.2

ERROR: InvocationError: /home/ubuntu/virtualenvs/venv-2.7.9/bin/python2.7 -m virtualenv --python /home/ubuntu/.pyenv/versions/3.2.5/bin/python3.2 py32 (see /home/ubuntu/tox-pyenv/.tox/py32/log/py32-0.log)
```


##### Not sure what the problem is here... I'm going to try to a rebuild without cache.


---------

https://circleci.com/gh/samstav/tox-pyenv/46

**Comment by samstav** [comment]
@rudineirk Looks like the CircleCI failure is related to these:

https://github.com/travis-ci/travis-ci/issues/5517
https://github.com/yyuu/pyenv/issues/531

**Comment by rudineirk** [comment]
Fixed the Python 3.2 build problem on #6 , I will rebase this pull request once that one is merged

**Comment by rudineirk** [comment]
ready for merge :)

**Comment by samstav** [comment]
@rudineirk, thanks for your contribution. [Pushed 1.0.3 to PyPI](https://pypi.python.org/pypi/tox-pyenv/1.0.3).

https://github.com/samstav/tox-pyenv/releases/tag/v1.0.3

**Pull request merged**
